### PR TITLE
mention tohora and how to use it in the readme

### PR DESCRIPTION
**Pull request by curcuz**

### CODE REVIEW

**Review by petrosagg — APPROVED** [review]

**Comment by curcuz** [comment]
@balena-ci retest

**Comment by idoodler** [comment]
I would really like this PR to be approved. Unexperienced users may have issues identify this service and port 8080 is a common port for other software to run. In a multicontainer project some services may just not work because of this.

At lease inform about it in the Readme.

@chrisys @shaunmulligan fyi

**Comment by chrisys** [comment]
@balena-ci retest

**Comment by chrisys** [comment]
@idoodler thanks for flagging it up - now merged.

**Pull request merged**
